export const GET_MARKET_DATA = 'GET_MARKET_DATA';
export const WATCH_SHARES_DATA = 'WATCH_SHARES_DATA';
export const UPDATE_SHARES_DATA = 'UPDATE_SHARES_DATA';

//Loading
export const SHOW_DASHBOARD_SPINNER = 'SHOW_DASHBOARD_SPINNER';
export const HIDE_DASHBOARD_SPINNER = 'HIDE_DASHBOARD_SPINNER';